### ISSUE TITLE
Error during write to Hive Acid Table Into Multiple Partitions

### ISSUE THREAD

**Issue by gowtamchandrahasa** [qubole/spark-acid#104]
Hi guys, 

We use spark to read from and write to hive acid tables. We were using HiveWarehouseConnector(HWC) before and moved to spark-acid library.
All our tables are Hive ACID tables and our partitions have a two-level nesting based on date and are created dynamically (origin_date, create_date  - yyyy-MM-dd format).

We are trying to write data into the hive table with the origin_date column ranging over about 300 dates.

 **We are getting an OOM error. We also know that the issue is not with the data size, since we have written the same data into a single partition by manipulating the field origin_date. So, we doubt the issue might be with writing to too many partitions. Below is the OOM error seen in the logs**
`java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.qubole.shaded.hadoop.hive.ql.exec.vector.ColumnVector.ensureSize(ColumnVector.java:232)
    at com.qubole.shaded.hadoop.hive.ql.exec.vector.BytesColumnVector.ensureSize(BytesColumnVector.java:547)
    at com.qubole.shaded.hadoop.hive.ql.exec.vector.StructColumnVector.ensureSize(StructColumnVector.java:136)
    at com.qubole.shaded.hadoop.hive.ql.io.orc.WriterImpl.setColumn(WriterImpl.java:258)
    at com.qubole.shaded.hadoop.hive.ql.io.orc.WriterImpl.setColumn(WriterImpl.java:237)
    at com.qubole.shaded.hadoop.hive.ql.io.orc.WriterImpl.setColumn(WriterImpl.java:261)
    at com.qubole.shaded.hadoop.hive.ql.io.orc.WriterImpl.setColumn(WriterImpl.java:237)
    at com.qubole.shaded.hadoop.hive.ql.io.orc.WriterImpl.setColumn(WriterImpl.java:237)
    at com.qubole.shaded.hadoop.hive.ql.io.orc.WriterImpl.addRow(WriterImpl.java:308)
    at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcRecordUpdater.addSimpleEvent(OrcRecordUpdater.java:424)
    at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcRecordUpdater.addSplitUpdateEvent(OrcRecordUpdater.java:432)
    at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcRecordUpdater.insert(OrcRecordUpdater.java:484)
    at com.qubole.spark.hiveacid.writer.hive.HiveAcidFullAcidWriter.process(HiveAcidWriter.scala:302)
    at com.qubole.spark.hiveacid.writer.TableWriter$$anon$1$$anonfun$apply$1.apply(TableWriter.scala:144)
    at com.qubole.spark.hiveacid.writer.TableWriter$$anon$1$$anonfun$apply$1.apply(TableWriter.scala:144)
    at scala.collection.Iterator$class.foreach(Iterator.scala:891)
    at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$11$$anon$1.foreach(WholeStageCodegenExec.scala:622)
    at com.qubole.spark.hiveacid.writer.TableWriter$$anon$1.apply(TableWriter.scala:144)
    at com.qubole.spark.hiveacid.writer.TableWriter$$anon$1.apply(TableWriter.scala:136)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
    at org.apache.spark.scheduler.Task.run(Task.scala:121)
    at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
    at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)`
    
    
**Then, we tried doubling the executor memory and increasing the spark.executor.memoryOverHead, then it took a long time but all the stages were successfully done, but then it again failed with a new error as below:**
`Caused by: com.qubole.shaded.thrift.TApplicationException: Internal error processing add_dynamic_partitions
    at com.qubole.shaded.thrift.TApplicationException.read(TApplicationException.java:111)
    at com.qubole.shaded.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
    at com.qubole.shaded.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_add_dynamic_partitions(ThriftHiveMetastore.java:5527)
    at com.qubole.shaded.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.add_dynamic_partitions(ThriftHiveMetastore.java:5514)
    at com.qubole.shaded.hadoop.hive.metastore.HiveMetaStoreClient.addDynamicPartitions(HiveMetaStoreClient.java:2669)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.qubole.shaded.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:208)
    at com.sun.proxy.$Proxy66.addDynamicPartitions(Unknown Source)
    at com.qubole.spark.hiveacid.transaction.HiveAcidTxnManager.addDynamicPartitions(HiveAcidTxnManager.scala:356)
    at com.qubole.spark.hiveacid.transaction.HiveAcidTxn.addDynamicPartitions(HiveAcidTxn.scala:110)
    at com.qubole.spark.hiveacid.writer.TableWriter.process(TableWriter.scala:218)
    at com.qubole.spark.hiveacid.HiveAcidOperationDelegate.insertInto(AcidOperationDelegate.scala:289)
    at com.qubole.spark.hiveacid.HiveAcidTable$$anonfun$insertInto$1.apply(HiveAcidTable.scala:129)
    at com.qubole.spark.hiveacid.HiveAcidTable$$anonfun$insertInto$1.apply(HiveAcidTable.scala:129)
    at com.qubole.spark.hiveacid.HiveTxnWrapper.inTxnRetry$1(HiveAcidTable.scala:330)
    at com.qubole.spark.hiveacid.HiveTxnWrapper.inTxn(HiveAcidTable.scala:355)
    at com.qubole.spark.hiveacid.HiveAcidTable.insertInto(HiveAcidTable.scala:128)
    at com.qubole.spark.hiveacid.datasource.HiveAcidDataSource.createRelation(HiveAcidDataSource.scala:62)
    at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
    at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
    at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
    at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
    at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
    at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
    at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
    at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
    at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
    at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:668)
    at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:276)
    at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:270)
    at com.myntra.vorta.store.executor.BatchWriteExecutor.writeData(BatchWriteExecutor.java:42)
    at com.myntra.vorta.store.manager.impl.BatchInteractionManagerImpl.write(BatchInteractionManagerImpl.java:104)
    at com.myntra.vorta.jobs.impl.migration.DataMigrationToNewNamespaceJob.run(DataMigrationToNewNamespaceJob.java:79)
    ... 6 more`
    
  
  As already said above we tried writing all the data into a single partition by manipulating the **origin_date** field, it succeeded within 10 minutes without any issues.
  
  PS: we can see staging temp folders created in blob, with all the dynamic partition folders created. But, there's no data in hive. Please find screenshots attached for the same.
  
  Has someone else face this issue? @amoghmargoor , Would like some help. 
  Thanks!
  
  
<img width="1080" alt="Screenshot 2020-12-29 at 2 42 33 PM" src="https://user-images.githubusercontent.com/60927037/103276765-768d9880-49ed-11eb-89f9-c0c19dfd446c.png">
<img width="1273" alt="Screenshot 2020-12-29 at 2 42 42 PM" src="https://user-images.githubusercontent.com/60927037/103276768-78eff280-49ed-11eb-8fc3-8bd13d84acdf.png">

**Comment by gowtamchandrahasa** [comment]
We found that the issue was with sql server unable to handle more than 2100 params at once, when the query is fired for too many partitions.
