### ISSUE TITLE
Table not found exception

### ISSUE THREAD

**Issue by tomas-duda** [qubole/spark-acid#12]
Hi,

I was trying to use the spark-acid library from pyspark 2.3.1 and got the InvalidTable exception. 
Specifically, I ran the following commands:

```
$ pyspark --jars spark-acid-0.4.0.jar
>>> spark.read.format("HiveAcid").option("table", "default.test_sa").load()
19/08/21 13:42:38 ERROR Hive: Table default.test_sa not found: spark.default.test_sa table not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/hdp/current/spark2-client/python/pyspark/sql/readwriter.py", line 172, in load
    return self._df(self._jreader.load())
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/hdp/current/spark2-client/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/hdp/current/spark2-client/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o75.load.
: com.qubole.shaded.hadoop.hive.ql.metadata.InvalidTableException: Table not found test_sa
        at com.qubole.shaded.hadoop.hive.ql.metadata.Hive.getTable(Hive.java:1133)
        at com.qubole.shaded.hadoop.hive.ql.metadata.Hive.getTable(Hive.java:1103)
        at com.qubole.spark.datasources.hiveacid.HiveAcidRelation.<init>(HiveAcidRelation.scala:67)
        at com.qubole.spark.datasources.hiveacid.HiveAcidDataSource.createRelation(HiveAcidDataSource.scala:34)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:340)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:745)
```

I'm running the HDP 3.0.1 Hadoop distribution with Hive 3.1. The Hive table was created using the following statements:

CREATE TABLE default.test_sa (a string, b string) STORED AS ORC;
INSERT INTO default.test_sa ('a', 'a'), ('b', 'b');

Am I using unsupported stack? Can you help me debug this issue?

Thank you

**Comment by somani** [comment]
Can you confirm that your spark was configured to talk to the same metastore as was used in hive. That would be done by setting hive.metastore.uris to point to a Hive Metastore Server backed by the same metastore db as used in Hive to create the table.

Does a "show tables" in Spark show the `default.test_sa` table?

**Comment by tomas-duda** [comment]
Well, Spark and Hive are using the same metastore database (`hive.metastore.uris` is the same) but each of them uses a separate metastore catalog.

SHOW TABLES in Spark does not show the `default.test_sa` table.

**Comment by somani** [comment]
I am not an expert on HDP setup, so please help me with some information.
The crux of your issue is that spark and hive on HDP seem to use different catalogs. For Spark to be able to see the tables created in Hive, we need it to talk to the same catalog as Hive. 

In your comment above:
"Well, Spark and Hive are using the same metastore database (hive.metastore.uris is the same) but each of them uses a separate metastore catalog."
Can you tell me what is the configuration in Spark that tells it to use a different catalog than hive. If they are using they same hive.metastore.uri, shouldn't they be using the same catalog as well, or is it somehow specified in spark to use a different catalog?

**Comment by tomas-duda** [comment]
OK, thank you for clarification.

Since HDP3, there is the "metastore.catalog.default" setting for Spark that overrides the value from the hive-site configuration. Hive metastore DB schema contains a table called CTLGS that stores data about different Hive catalogs, e.g.:

```
mysql> select * from CTLGS;
+------------+-------+----------------------------+-------------------------------------------------+
| CTLG_ID    | NAME  | DESC                       | LOCATION_URI                                    |
+------------+-------+----------------------------+-------------------------------------------------+
|          1 | hive  | Default catalog for Hive   | hdfs://hadoop/warehouse/tablespace/managed/hive |
| 1073741824 | spark | Default catalog for Spark  | hdfs://hadoop/apps/spark/warehouse              |
+------------+-------+----------------------------+-------------------------------------------------+
```

The DBS table now has an additional column "CTLG_NAME" that informs Hive/Spark about the catalog in which the database belongs.

**Comment by somani** [comment]
I think I understand the issue now. We should be able to support this with some code changes, but trying to think of a workaround.
Can you please try running pyspark with 
`pyspark --conf spark.hadoop.metastore.catalog.default=hive` and see if it works?

**Comment by tomas-duda** [comment]
Yes, it seems to work now:
```
$ pyspark --conf spark.hadoop.metastore.catalog.default=hive --jars spark-acid-0.4.0.jar

>>> sql("show tables").show()
+--------+-------------+-----------+
|database|    tableName|isTemporary|
+--------+-------------+-----------+
| default|      test_sa|      false|
+--------+-------------+-----------+

>>> spark.read.format("HiveAcid").option("table", "default.test_sa").load().collect()
[Row(a=u'a', b=u'a'), Row(a=u'b', b=u'b')]
```
Thanks for help!
