### ISSUE TITLE
 illegal state exception in read code flow.

### ISSUE THREAD

**Issue by citrusraj** [qubole/spark-acid#19]
```[info]   org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 16.0 failed 1 times, most recent failure: Lost task 0.0 in stage 16.0 (TID 112, localhost, executor driver): java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING_END[info] 	at java.nio.charset.CharsetDecoder.throwIllegalStateException(CharsetDecoder.java:992)[info] 	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:572)[info] 	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:802)[info] 	at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcRecordUpdater.parseKeyIndex(OrcRecordUpdater.java:628)[info] 	at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcRawRecordMerger.discoverKeyBounds(OrcRawRecordMerger.java:744)[info] 	at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcRawRecordMerger.<init>(OrcRawRecordMerger.java:1007)[info] 	at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcInputFormat.getReader(OrcInputFormat.java:2091)[info] 	at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcInputFormat.getRecordReader(OrcInputFormat.java:1989)[info] 	at com.qubole.spark.datasources.hiveacid.reader.Hive3RDD$$anon$1.liftedTree1$1(Hive3Rdd.scala:287)[info] 	at com.qubole.spark.datasources.hiveacid.reader.Hive3RDD$$anon$1.<init>(Hive3Rdd.scala:286)[info] 	at com.qubole.spark.datasources.hiveacid.reader.Hive3RDD.compute(Hive3Rdd.scala:253)[info] 	at com.qubole.spark.datasources.hiveacid.reader.Hive3RDD.compute(Hive3Rdd.scala:86)[info] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)[info] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)[info] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)[info] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)[info] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)[info] 	at org.apache.spark.rdd.UnionRDD.compute(UnionRDD.scala:105)[info] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)[info] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)[info] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)[info] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)[info] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)[info] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)[info] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)[info] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)[info] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)[info] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)[info] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)[info] 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)[info] 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)[info] 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)[info] 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)[info] 	at org.apache.spark.scheduler.Task.run(Task.scala:121)[info] 	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)[info] 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)[info] 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[info] 	at java.lang.Thread.run(Thread.java:748)[info][info] Driver stacktrace:[info]   at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1877)[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1876)[info]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)[info]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)[info]   at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1876)[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)[info]   at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)[info]   at scala.Option.foreach(Option.scala:257)[info]   at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)[info]   ...[info]   Cause: java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING_END[info]   at java.nio.charset.CharsetDecoder.throwIllegalStateException(CharsetDecoder.java:992)[info]   at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:572)[info]   at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:802)[info]   at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcRecordUpdater.parseKeyIndex(OrcRecordUpdater.java:628)[info]   at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcRawRecordMerger.discoverKeyBounds(OrcRawRecordMerger.java:744)[info]   at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcRawRecordMerger.<init>(OrcRawRecordMerger.java:1007)[info]   at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcInputFormat.getReader(OrcInputFormat.java:2091)[info]   at com.qubole.shaded.hadoop.hive.ql.io.orc.OrcInputFormat.getRecordReader(OrcInputFormat.java:1989)[info]   at com.qubole.spark.datasources.hiveacid.reader.Hive3RDD$$anon$1.liftedTree1$1(Hive3Rdd.scala:287)[info]   at com.qubole.spark.datasources.hiveacid.reader.Hive3RDD$$anon$1.<init>(Hive3Rdd.scala:286)```

**Comment by citrusraj** [comment]
https://github.com/qubole/spark-acid/pull/31

**Comment by citrusraj** [comment]
https://github.com/qubole/spark-acid/commit/2e66f76b3a3c974a73f03d9e80d9c66a0475a552
