### ISSUE TITLE
Setting NO_AUTO_COMPACTION for Hive Table

### ISSUE THREAD

**Issue by shuwnyuantee** [qubole/spark-acid#42]
Referring to your doc:  https://github.com/qubole/spark-acid#design-constraints  => item (3)

It mentions about `To disable automatic compaction on table` with:

`ALTER TABLE <> SET TBLPROPERTIES ("NO_AUTO_COMPACTION"="true")`

We have a Hive table which is continuously written into via Spark Structured Streaming with:

`val output_stream_df = data.writeStream.format("HiveAcid")....`

Is it compulsory to set `"NO_AUTO_COMPACTION"="true"` on this table?

Does it mean we need to handle compaction manually? What is the suggested approach to handle this? 

What came to my mind is to schedule a cron job to do the table compaction manually, something like this:

- stop the Spark app (app1) that streams (writes) into the Hive table (myTable)
- do table compaction: ALTER TABLE myTable COMPACT 'minor' / 'major'
- start Spark app1 

Does this make sense to you? If not, is there any example / link on how to handle this?

From your source code, I found this:
`src/main/scala/com/qubole/spark/hiveacid/streaming/HiveAcidSinkOptions.scala:  val COMPACT_INTERVAL_KEY = "spark.acid.streaming.log.compactInterval"`

Does this related to table compaction I mentioned above? By setting `spark.acid.streaming.log.compactInterval`, will `Spark Acid` automatically handle the table compaction for us?

Thanks!

**Comment by amoghmargoor** [comment]
Hi @shuwnyuantee 

The reason AUTO_COMPACTION is being asked to disabled is because of the following

When RDD for ACID table is returned to be read it does not hold any Locks on the table. Now, if RDD is being read it will create partitions using RDD.getPartitions() based on ACID files under base and delta directories. While reading those partitions, those underlying files should not be deleted as the read operation would fail. Compaction either Minor or Major does exactly this. After compacting it goes ahead cleaning up the old files on which RDD partitions might have been created upon. Hence read may fail if reading and compaction collides.

So automatic compaction is asked to disable to avoid collision. We recommend users to schedule compaction during hours when no one would be reading the tables using `ALTER TABLE <> COMPACT <>`. But it's just a recommendation and users can avoid setting "NO_AUTO_COMPACTION"="true" if they can ensure reads and compaction don't happen at same time. 
But Note, Append operations being done in Streaming can happen in parallel to the compaction. That should not be an issue.

Regarding `COMPACT_INTERVAL_KEY = "spark.acid.streaming.log.compactInterval"` this is related to CompactibleFileStreamLog: ref: https://jaceklaskowski.gitbooks.io/spark-structured-streaming/spark-sql-streaming-CompactibleFileStreamLog.html  Not related to HiveCompaction which we are talking above.

**Comment by shuwnyuantee** [comment]
@amoghmargoor  From your explanation, it seems AUTO_COMPACTION only needs to be disabled if `hive-acid` datasource is used for read in Spark code.


However, in our scenario, we only use `hive-acid` datasource for write, here's our code snippet:

```
val output_stream_df = data.writeStream.format("HiveAcid")
  .option("database", "default")
  .option("table", "events_sink")
  .option("checkpointLocation", "/user/spark/events/checkpoint")
  .option("spark.acid.streaming.log.metadataDir", "/user/spark/events/checkpoint/spark-acid")
  .option("metastoreUri", "thrift://hive-metastore:9083")
  .trigger(Trigger.ProcessingTime("30 seconds"))
  .start()
```

We didn't read the table in Spark via `hive-acid` datasource. Table read only happens via `beeline` or `Zeppelin notebook`.

So for our use case, it is not required to disable AUTO_COMPACTION at all, am I right?

Thanks for your prompt reply 👍

**Comment by amoghmargoor** [comment]
Hi @shuwnyuantee,
Sure, if you are not reading the tables via spark, then it should be fine to allow auto compaction. `beeline` should connect to Hive I suppose but Zeppelin may still go via Spark I guess.

Btw you will need this commit for proper compactions, so make sure you have them in your jar:
https://github.com/qubole/spark-acid/commit/736ffa3d5f68ef65714504f148f8530efd873cec

If you don't mind asking which company is this and at what stage are you guys in using this datasource ?

**Comment by shuwnyuantee** [comment]
@amoghmargoor  Thanks for your friendly reminder, we will build our jar base on latest master.

We are from Rapid River, a software consultancy company in Malaysia. We collect Clickstream events from websites into Kafka, & uses `spark-acid` as write stream into Hive Table. Currently we are at a stage very near to production deployment.

Thanks again for publishing this library & all your help! 👍

**Comment by amoghmargoor** [comment]
you are most welcome @shuwnyuantee ... for any issues you find, please feel free to contact me or @sourabh912. we will be glad to support you in your journey to production.

**Comment by shuwnyuantee** [comment]
@amoghmargoor  We are using Spark-Acid latest master code, which contains commit `736ffa3` that you suggested to include about dynamic partition. However, we came across this error now:

1) In the driver error log:

```
NoSuchTxnException: No such transaction txnid:22521
    at com.qubole.shaded.hadoop.hive.metastore.api.ThriftHiveMetastore$add_dynamic_partitions_result$add_dynamic_partitions_resultStandardScheme.read(ThriftHiveMetastore.java)
    at com.qubole.shaded.hadoop.hive.metastore.api.ThriftHiveMetastore$add_dynamic_partitions_result$add_dynamic_partitions_resultStandardScheme.read(ThriftHiveMetastore.java)
    at com.qubole.shaded.hadoop.hive.metastore.api.ThriftHiveMetastore$add_dynamic_partitions_result.read(ThriftHiveMetastore.java)
    at com.qubole.shaded.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
    at com.qubole.shaded.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_add_dynamic_partitions(ThriftHiveMetastore.java:5527)
...
(28 additional frame(s) were not displayed)

StreamingQueryException: Query hiveSink [id = 3267e047-4848-4821-a2f7-04d6b8dd84c9, runId = c94a4e2e-34bc-48cf-8f2f-266057cf4c84] terminated with exception: No such transaction txnid:22521
    at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:297)
    at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193) 
```


```
NoSuchTxnException: No such transaction txnid:22521
    at com.qubole.shaded.hadoop.hive.metastore.api.ThriftHiveMetastore$add_dynamic_partitions_result$add_dynamic_partitions_resultStandardScheme.read(ThriftHiveMetastore.java)
    at com.qubole.shaded.hadoop.hive.metastore.api.ThriftHiveMetastore$add_dynamic_partitions_result$add_dynamic_partitions_resultStandardScheme.read(ThriftHiveMetastore.java)
    at com.qubole.shaded.hadoop.hive.metastore.api.ThriftHiveMetastore$add_dynamic_partitions_result.read(ThriftHiveMetastore.java)
    at com.qubole.shaded.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
    at com.qubole.shaded.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_add_dynamic_partitions(ThriftHiveMetastore.java:5527)
...
(28 additional frame(s) were not displayed)
```

2) In the worker error log

```
ERROR AcidUtils: Failed to create hdfs://.../warehouse/tablespace/managed/hive/events/year=2020/month=6/day=4/delta_0000727_0000727/_or
c_acid_version due to: Failed to CREATE_FILE /warehouse/tablespace/managed/hive/events/year=2020/month=6/day=4/delta_0000727_0000727/_orc_acid_version for DFSClient_NONMAPREDUCE_-528742007_48
 on 10.236.7.228 because DFSClient_NONMAPREDUCE_-528742007_48 is already the current lease holder.
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.recoverLeaseInternal(FSNamesystem.java:2555)
        at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.startFile(FSDirWriteFileOp.java:378)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2453)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2351)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:774)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:462)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:876)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:822)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2682)
```

Any clue regarding this? Can it be related to the latest dynamic partitioning changes?

**Comment by amoghmargoor** [comment]
yes @shuwnyuantee this is due to adding dynamic partitions. We will look into it ASAP: https://github.com/qubole/spark-acid/issues/54
