### ISSUE TITLE
Merge condition in merge sql command does not support table names

### ISSUE THREAD

**Issue by sourabh912** [qubole/spark-acid#73]
Merge statement like this 
`merge into mtbl1 using mtbl2 on mtbl1.id=mtbl2.id when not matched then insert values (*) when matched and mtbl1.name != mtbl2.name then  update set name=mtbl2.name`

fails with the following error: 

`org.apache.spark.sql.AnalysisException: `mtbl1.id` resolution failed given these columns: name,id,name,id; line 1 pos 32
  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
  at org.apache.spark.sql.SqlUtils$$anonfun$resolveReferences$3.apply(SqlUtils.scala:61)
  at org.apache.spark.sql.SqlUtils$$anonfun$resolveReferences$3.apply(SqlUtils.scala:60)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.sql.SqlUtils$.resolveReferences(SqlUtils.scala:59)
  at org.apache.spark.sql.catalyst.parser.plans.logical.MergePlan$.resolve(MergePlan.scala:37)
  at com.qubole.spark.hiveacid.merge.MergeImpl.<init>(MergeImpl.scala:72)
  at com.qubole.spark.hiveacid.HiveAcidOperationDelegate.merge(AcidOperationDelegate.scala:442)
  at com.qubole.spark.hiveacid.HiveAcidTable$$anonfun$merge$1.apply(HiveAcidTable.scala:199)
  at com.qubole.spark.hiveacid.HiveAcidTable$$anonfun$merge$1.apply(HiveAcidTable.scala:199)
  at com.qubole.spark.hiveacid.HiveTxnWrapper.inTxnRetry$1(HiveAcidTable.scala:330)
  at com.qubole.spark.hiveacid.HiveTxnWrapper.inTxn(HiveAcidTable.scala:355)
  at com.qubole.spark.hiveacid.HiveAcidTable.merge(HiveAcidTable.scala:198)
  at com.qubole.spark.hiveacid.datasource.HiveAcidRelation.merge(HiveAcidRelation.scala:98)
  at com.qubole.spark.datasources.hiveacid.sql.catalyst.plans.command.MergeCommand.run(MergeCommand.scala:51)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:79)
  at org.apache.spark.sql.Dataset$$anonfun$6.apply(Dataset.scala:195)
  at org.apache.spark.sql.Dataset$$anonfun$6.apply(Dataset.scala:195)
  at org.apache.spark.sql.Dataset$$anonfun$53.apply(Dataset.scala:3370)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:79)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:126)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:74)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3369)
  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:195)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:79)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:662)
  ... 49 elided`

**Comment by sourabh912** [comment]
Commit ID: https://github.com/qubole/spark-acid/commit/a39813e9d4e19a70971c57568527777b65f1c3c5
